module.exports = {
    AddArtistCommand:            require('./AddArtistCommand'),
    AddTrackCommand:             require('./AddTrackCommand'),
    AddAlbumCommand:             require('./AddAlbumCommand'),
    GetArtistByIdCommand:        require('./GetArtistByIdCommand'),
    RemoveArtistCommand:         require('./RemoveArtistCommand'),
    RemoveAlbumCommand:          require('./RemoveAlbumCommand'),
    GetAlbumByIdCommand:         require('./GetAlbumByIdCommand'),
    GetTrackByIdCommand:         require('./GetTrackByIdCommand'),
    ArtistsCommand:              require('./ArtistsCommand'),
    AlbumsCommand:               require('./AlbumsCommand'),
    TracksCommand:               require('./TracksCommand'),
    PlaylistsCommand:            require('./PlaylistsCommand'),
    RemoveTrackCommand:          require('./RemoveTrackCommand'),
    CreatePlaylistCommand:       require('./CreatePlaylistCommand'),
    SearchByNamePartial  :       require('./SearchByNamePartial'),
    GetTracksMatchingArtistName: require('./GetTracksMatchingArtistName'),
    GetTracksMatchingGenres:     require('./GetTracksMatchingGenres'),
    RemovePlaylistCommand:       require('./RemovePlaylistCommand'),
    FindByCommand:               require('./FindByCommand'),
    FilterAllByCommand:          require('./FilterAllByCommand')
 }